# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      # - .:/var/www #local
      # - ./vendor:/var/www/vendor #local
      - ./storage:/var/www/storage

    networks:
      - bms-backend_laravel
    expose:
    - "9000"  # Expose port 9000 internally for Nginx
    depends_on:
      - postgres
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=dpg-cs9l9u3qf0us739i30m0-a
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      # - APP_URL=http://localhost #local
      - APP_URL=https://my-bms-laravel.onrender.com
      # - APP_ENV=local
      - APP_ENV=production
      - APP_KEY=${APP_KEY}

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      # - "9000:80" #local
      - "80:80" #production
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - .:/var/www #local
      - ./storage:/var/www/storage #production
    networks:
      - bms-backend_laravel
    depends_on:
      - app

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bms-backend_laravel

volumes:
  postgres_data:
    driver: local

networks:
  bms-backend_laravel:
    driver: bridge